#h2 http://localhost:8080/h2-console
spring:
 #datasource:
  #driver-class-name: org.h2.Driver
  #url: jdbc:h2:mem:pictgram
  #username: sa
  #password:
  
 #h2:
  #console:
   #enable: true
  
 jpa:
   database: POSTGRESQL
 datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/pictgram
    username: pictgram
    password: password
debug: true
image:
  local: true